version: '3.9'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.node1
    container_name: node1
    networks:
      mariadb_network:
        ipv4_address: 10.1.0.10
    environment:
      MYSQL_ROOT_PASSWORD: node1
    volumes:
      - ./node1.cnf:/etc/mysql/conf.d/server.cnf:ro
      - node1_data:/data
      - node1_log:/log
      - node1_backup:/backup
      - node1_tools:/tools
    ports:
      - "3336:3306"
    cap_add:
      - SYS_TIME

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node2
    container_name: node2
    networks:
      mariadb_network:
        ipv4_address: 10.1.0.20
    environment:
      MYSQL_ROOT_PASSWORD: node2
      MYSQL_MASTER_PASSWORD: node1
    volumes:
      - ./node2.cnf:/etc/mysql/conf.d/server.cnf:ro
      - node2_data:/data
      - node2_log:/log
      - node2_backup:/backup
      - node2_tools:/tools
    ports:
      - "3337:3306"
    cap_add:
      - SYS_TIME
    depends_on:
      - node1

  maxscale:
    image: mariadb/maxscale:24.02
    container_name: maxscale
    networks:
      mariadb_network:
        ipv4_address: 10.1.0.50
    #environment:
    #  MYSQL_ROOT_PASSWORD: myrootpassword
    #  MYSQL_DATABASE: mydatabase
    #  MYSQL_USER: myuser
    #  MYSQL_PASSWORD: mypassword
    #  MYSQL_INITDB_SKIP_TZINFO: "1"
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf.d/maxscale.cnf:ro
      #- maxscale_data:/var/lib/maxscale
      #- maxscale_log:/var/log/maxscale
    ports:
      - "3338:3306"
      #- "8989:8989"
    depends_on:
      - node1
      - node2

  #monitoring:
    #image: mariadb:10.6.20
    #container_name: monitoring
    #networks:
    #  mariadb_network:
    #    ipv4_address: 10.1.0.60
    #environment:
    #  MYSQL_ROOT_PASSWORD: myrootpassword
    #  MYSQL_DATABASE: mydatabase
    #  MYSQL_USER: myuser
    #  MYSQL_PASSWORD: mypassword
    #  MYSQL_INITDB_SKIP_TZINFO: "1"
    #volumes:
    #  - ./server.cnf:/etc/mysql/conf.d/server.cnf:ro
    #  - mariadb_data:/var/lib/mysql
    #  - ./keyfile:/etc/mysql/keyfile:ro
    #  - ./ssl:/etc/mysql/ssl:ro
    #ports:
    #  - "3336:3306"

volumes:
  node1_data:
  node1_log:
  node1_backup:
  node1_tools:
  node2_data:
  node2_log:
  node2_backup:
  node2_tools:
  maxscale_data:
  #max_scale_data:
  #maxscale_log:
  #mon_data:

networks:
  mariadb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24